cd E:\work\link_extractor\ResearchGateSpider

scrapy crawl RGSpider1 -a start_url=http://uconn.edu/ -a domain=uconn.edu -a university="University of Connecticut"
scrapy crawl RGSpider1 -a start_url=http://www.usf.edu/ -a domain=usf.edu -a university="University of South Florida"
scrapy crawl RGSpider1 -a start_url=http://www.smu.edu/ -a domain=smu.edu -a university="Southern Methodist University"
scrapy crawl RGSpider1 -a start_url=https://umich.edu/ -a domain=umich.edu -a university="University of Michigan-Ann Arbor"
scrapy crawl RGSpider1 -a start_url=https://www.syracuse.edu/ -a domain=syracuse.edu -a university="Syracuse University"
scrapy crawl RGSpider1 -a start_url=http://www.utexas.edu/ -a domain=utexas.edu -a university="The University of Texas at Austin"
scrapy crawl RGSpider1 -a start_url=https://www.stevens.edu/ -a domain=stevens.edu -a university="Stevens Institute of Technology"
scrapy crawl RGSpider1 -a start_url=http://www.esf.edu/ -a domain=esf.edu -a university="State University of New York College of Environmental Science and Forestry"
scrapy crawl RGSpider1 -a start_url=http://www.nova.edu/ -a domain=nova.edu -a university="Nova Southeastern University"
scrapy crawl RGSpider1 -a start_url=https://utulsa.edu/ -a domain=utulsa.edu -a university="University of Tulsa"
scrapy crawl RGSpider1 -a start_url=http://www.buffalo.edu/ -a domain=buffalo.edu -a university="SUNY at Buffalo"
scrapy crawl RGSpider1 -a start_url=http://www.gsu.edu/ -a domain=gsu.edu -a university="Georgia State University"
scrapy crawl RGSpider1 -a start_url=http://www.american.edu/ -a domain=american.edu -a university="American University"
scrapy crawl RGSpider1 -a start_url=http://www.ucsb.edu/ -a domain=ucsb.edu -a university="University of California-Santa Barbara"
scrapy crawl RGSpider1 -a start_url=http://www.newschool.edu/ -a domain=newschool.edu -a university="The New School  New York"
scrapy crawl RGSpider1 -a start_url=https://www.barry.edu/ -a domain=barry.edu -a university="Barry University"
scrapy crawl RGSpider1 -a start_url=https://www2.howard.edu/ -a domain=howard.edu -a university="Howard University"
scrapy crawl RGSpider1 -a start_url=http://www.hartford.edu/ -a domain=hartford.edu -a university="University of Hartford"


scrapy crawl RGSpider1 -a start_url=http://www.clemson.edu/ -a domain=clemson.edu -a university="Clemson University  Clemson"
scrapy crawl RGSpider1 -a start_url=https://www2.gmu.edu/ -a domain=gmu.edu -a university="George Mason University  Fairfax"
scrapy crawl RGSpider1 -a start_url=https://www.fsu.edu/ -a domain=fsu.edu -a university="Florida State University  Tallahassee"
scrapy crawl RGSpider1 -a start_url=http://www.clemson.edu/ -a domain=utdallas.edu -a university="The University of Texas at Dallas  Richardson"
scrapy crawl RGSpider1 -a start_url=http://www.uta.edu/uta/ -a domain=uta.edu -a university="The University of Texas at Arlington  Arlington"
scrapy crawl RGSpider1 -a start_url=http://www.pitt.edu/ -a domain=pitt.edu -a university="University of Pittsburgh"
scrapy crawl RGSpider1 -a start_url=http://www.albany.edu/ -a domain=albany.edu -a university="SUNY at Albany  Albany"
scrapy crawl RGSpider1 -a start_url=http://www.clarku.edu/ -a domain=clarku.edu -a university="Clark University  Worcester"
scrapy crawl RGSpider1 -a start_url=http://newbrunswick.rutgers.edu/ -a domain=newbrunswick.rutgers.edu -a university="Rutgers University-New Brunswick  New Brunswick"
scrapy crawl RGSpider1 -a start_url=http://web.iit.edu/ -a domain=iit.edu -a university="Illinois Institute of Technology  Chicago"
scrapy crawl RGSpider1 -a start_url=http://www.fau.edu/ -a domain=fau.edu -a university="Florida Atlantic University"
scrapy crawl RGSpider1 -a start_url=https://twin-cities.umn.edu/ -a domain=umn.edu -a university="University of Minnesota-Twin Cities"
scrapy crawl RGSpider1 -a start_url=http://www.bridgeport.edu/ -a domain=bridgeport.edu -a university="University of Bridgeport  Bridgeport"
scrapy crawl RGSpider1 -a start_url=https://www.usm.edu/ -a domain=usm.edu -a university="University of Southern Mississippi  Hattiesburg"
scrapy crawl RGSpider1 -a start_url=http://www.uga.edu/ -a domain=uga.edu -a university="University of Georgia  Athens"
scrapy crawl RGSpider1 -a start_url=http://www.psu.edu/ -a domain=psu.edu -a university="Pennsylvania State University"
scrapy crawl RGSpider1 -a start_url=http://www.bu.edu/ -a domain=bu.edu -a university="Boston University  Boston"
scrapy crawl RGSpider1 -a start_url=https://www.osu.edu/ -a domain=osu.edu -a university="Ohio State University"
scrapy crawl RGSpider1 -a start_url=http://www.pacific.edu/ -a domain=pacific.edu -a university="University of the Pacific"
scrapy crawl RGSpider1 -a start_url=http://www.stjohns.edu/ -a domain=stjohns.edu -a university="St. John's University-New York"
scrapy crawl RGSpider1 -a start_url=http://www.udel.edu/ -a domain=udel.edu -a university="University of Delaware"
scrapy crawl RGSpider1 -a start_url=http://www.unh.edu/ -a domain=unh.edu -a university="University of New Hampshire"
scrapy crawl RGSpider1 -a start_url=https://laverne.edu/ -a domain=laverne.edu -a university="University of La Verne"
scrapy crawl RGSpider1 -a start_url=http://www.regent.edu/ -a domain=regent.edu -a university="Regent University"
scrapy crawl RGSpider1 -a start_url=https://www.ucf.edu/ -a domain=ucf.edu -a university="University of Central Florida"
scrapy crawl RGSpider1 -a start_url=https://uci.edu/ -a domain=uci.edu -a university="University of California-Irvine"
scrapy crawl RGSpider1 -a start_url=http://www.umkc.edu/ -a domain=umkc.edu -a university="University of Missouri-Kansas City"
scrapy crawl RGSpider1 -a start_url=https://www.mines.edu/ -a domain=mines.edu -a university="Colorado School of Mines"




scrapy crawl RGSpider1 -a start_url=https://www.umb.edu/ -a domain=umb.edu -a university="University of Massachusetts-Boston  Boston"
scrapy crawl RGSpider1 -a start_url=https://www.ncsu.edu/ -a domain=ncsu.edu -a university="North Carolina State University"
scrapy crawl RGSpider1 -a start_url=http://www.vcu.edu/ -a domain=vcu.edu -a university="Virginia Commonwealth University"
scrapy crawl RGSpider1 -a start_url=https://www.uark.edu/ -a domain=uark.edu -a university="University of Arkansas"
scrapy crawl RGSpider1 -a start_url=https://www.tiu.edu/ -a domain=tiu.edu -a university="Trinity International University"
scrapy crawl RGSpider1 -a start_url=http://www.hofstra.edu/home/index.html -a domain=hofstra.edu -a university="Hofstra University  Hempstead"
scrapy crawl RGSpider1 -a start_url=http://www.sc.edu/ -a domain=sc.edu -a university="University of South Carolina"
scrapy crawl RGSpider1 -a start_url=http://www.gatech.edu/ -a domain=gatech.edu -a university="Georgia Institute of Technology"
scrapy crawl RGSpider1 -a start_url=https://www.ua.edu/ -a domain=ua.edu -a university="The University of Alabama  Tuscaloosa"
scrapy crawl RGSpider1 -a start_url=http://www.njit.edu/ -a domain=njit.edu -a university="New Jersey Institute of Technology"
scrapy crawl RGSpider1 -a start_url=http://www.tnstate.edu/ -a domain=tnstate.edu -a university="Tennessee State University"
scrapy crawl RGSpider1 -a start_url=https://www.washington.edu/ -a domain=washington.edu -a university="University of Washington"
scrapy crawl RGSpider1 -a start_url=https://www.unt.edu/ -a domain=unt.edu -a university="University of North Texas"
scrapy crawl RGSpider1 -a start_url=http://www.wisc.edu/ -a domain=wisc.edu -a university="University of Wisconsin-Madison"
scrapy crawl RGSpider1 -a start_url=https://www.wpi.edu/ -a domain=wpi.edu -a university="Worcester Polytechnic Institute"
scrapy crawl RGSpider1 -a start_url=https://www.umass.edu/ -a domain=umass.edu -a university="University of Massachusetts Amherst"
scrapy crawl RGSpider1 -a start_url=http://www.montana.edu/ -a domain=montana.edu -a university="Montana State University  Bozeman"
scrapy crawl RGSpider1 -a start_url=http://www.cau.edu/ -a domain=cau.edu -a university="Clark Atlanta University"
scrapy crawl RGSpider1 -a start_url=http://www.memphis.edu/ -a domain=memphis.edu -a university="University of Memphis  Memphis"
scrapy crawl RGSpider1 -a start_url=http://www.widener.edu/ -a domain=widener.edu -a university="Widener University"
scrapy crawl RGSpider1 -a start_url=https://www.usfca.edu/ -a domain=usfca.edu -a university="University of San Francisco "
scrapy crawl RGSpider1 -a start_url=https://www.vt.edu/ -a domain=vt.edu -a university="Virginia Polytechnic Institute and State University  Blacksburg"
scrapy crawl RGSpider1 -a start_url=http://marquette.edu/ -a domain=marquette.edu -a university="Marquette University  Milwaukee"
scrapy crawl RGSpider1 -a start_url=https://www.ucdavis.edu/ -a domain=ucdavis.edu -a university="University of California-Davis  Davis"
scrapy crawl RGSpider1 -a start_url=https://www.unlv.edu/ -a domain=unlv.edu -a university="University of Nevada-Las Vegas  Las Vegas"
scrapy crawl RGSpider1 -a start_url=https://manoa.hawaii.edu/ -a domain=manoa.hawaii.edu -a university="University of Hawaii at Manoa  Honolulu"
scrapy crawl RGSpider1 -a start_url=http://www.adelphi.edu/ -a domain=adelphi.edu -a university="Adelphi University  Garden City"
scrapy crawl RGSpider1 -a start_url=http://www.ucdenver.edu/pages/ucdwelcomepage.aspx -a domain=ucdenver.edu -a university="University of Colorado Denver"
scrapy crawl RGSpider1 -a start_url=https://umbc.edu/ -a domain=umbc.edu -a university="University of Maryland-Baltimore County  Baltimore"
scrapy crawl RGSpider1 -a start_url=http://www.auburn.edu/ -a domain=auburn.edu -a university="Auburn University"
scrapy crawl RGSpider1 -a start_url=https://www.temple.edu/ -a domain=temple.edu -a university="Temple University"
scrapy crawl RGSpider1 -a start_url=https://www.yu.edu/ -a domain=yu.edu -a university="Yeshiva University"
scrapy crawl RGSpider1 -a start_url=http://www.niu.edu/index.shtml -a domain=niu.edu -a university="Northern Illinois University"
scrapy crawl RGSpider1 -a start_url=http://www.uvm.edu/ -a domain=uvm.edu -a university="University of Vermont"
scrapy crawl RGSpider1 -a start_url=https://www.uml.edu/ -a domain=uml.edu -a university="University of Massachusetts-Lowell"
scrapy crawl RGSpider1 -a start_url=https://www.indiana.edu/ -a domain=indiana.edu -a university="Indiana University-Bloomington"
scrapy crawl RGSpider1 -a start_url=http://www.indstate.edu/ -a domain=indstate.edu -a university="Indiana State University"
scrapy crawl RGSpider1 -a start_url=https://www.iupui.edu/ -a domain=iupui.edu -a university="Indiana University-Purdue University-Indianapolis"
scrapy crawl RGSpider1 -a start_url=http://siu.edu/ -a domain=siu.edu -a university="Southern Illinois University Carbondale"
scrapy crawl RGSpider1 -a start_url=http://louisville.edu/ -a domain=louisville.edu -a university="University of Louisville"
scrapy crawl RGSpider1 -a start_url=https://www.pdx.edu/ -a domain=pdx.edu -a university="Portland State University"
scrapy crawl RGSpider1 -a start_url=https://www.unm.edu/ -a domain=unm.edu -a university="University of New Mexico"
scrapy crawl RGSpider1 -a start_url=http://illinois.edu/ -a domain=illinois.edu -a university="University of Illinois at Urbana"
scrapy crawl RGSpider1 -a start_url=https://uwf.edu/ -a domain=uwf.edu -a university="The University of West Florida"
scrapy crawl RGSpider1 -a start_url=http://www.iup.edu/ -a domain=iup.edu -a university="Indiana University of Pennsylvania"
scrapy crawl RGSpider1 -a start_url=https://www.utk.edu/ -a domain=utk.edu -a university="The University of Tennessee"
scrapy crawl RGSpider1 -a start_url=https://www.twu.edu/ -a domain=twu.edu -a university="Texas Woman's University"
scrapy crawl RGSpider1 -a start_url=http://drexel.edu/ -a domain=drexel.edu -a university="Drexel University"
scrapy crawl RGSpider1 -a start_url=http://cms.bsu.edu/ -a domain=cms.bsu.edu -a university="Ball State University"
scrapy crawl RGSpider1 -a start_url=https://www.tamu.edu/ -a domain=tamu.edu -a university="Texas A & M University "


scrapy crawl RGSpider1 -a start_url=https://www.uncg.edu/ -a domain=uncg.edu -a university="University of North Carolina at Greensboro"
scrapy crawl RGSpider1 -a start_url=http://www.csuohio.edu/ -a domain=csuohio.edu -a university="Cleveland State University"
scrapy crawl RGSpider1 -a start_url=http://www.uncc.edu/ -a domain=uncc.edu -a university="University of North Carolina at Charlotte"
scrapy crawl RGSpider1 -a start_url=http://engineering.nyu.edu/ -a domain=engineering.nyu.edu -a university="Polytechnic University"
scrapy crawl RGSpider1 -a start_url=https://www.cmich.edu/ -a domain=cmich.edu -a university="Central Michigan University"
scrapy crawl RGSpider1 -a start_url=http://www.luc.edu/ -a domain=luc.edu -a university="Loyola University Chicago"
scrapy crawl RGSpider1 -a start_url=http://www.apu.edu/?SearchEngine=Google&Keyword=azusa%20pacific%20university&Campaign=Brand&a=1865&TrackingCode=sD9DXgUOV_dc|pcrid|71730721026|pkw|azusa%20pacific%20university|pmt|e&c3apimn=D9DXgUOV&ClientMarketingCampaignID=26&VendorAccountID=41856&gclid=CjwKEAjwkq7GBRDun9iu2JjyhmsSJADHCD_HstnPd4qM62pKYI1gAzLe3OIXUuHJJ46N0g2ODYxGEhoCJFvw_wcB -a domain=apu.edu? -a university="Azusa Pacific University"
scrapy crawl RGSpider1 -a start_url=http://www.lsu.edu/ -a domain=lsu.edu -a university="Louisiana State University and Agricultural & Mechanical College"
scrapy crawl RGSpider1 -a start_url=https://msu.edu/ -a domain=msu.edu -a university="Michigan State University"
scrapy crawl RGSpider1 -a start_url=https://home.byu.edu/ -a domain=byu.edu -a university="Brigham Young University"
scrapy crawl RGSpider1 -a start_url=http://www.du.edu/ -a domain=du.edu -a university="University of Denver  Denver"
scrapy crawl RGSpider1 -a start_url=http://www.duq.edu/ -a domain=duq.edu -a university="Duquesne University  Pittsburgh"
scrapy crawl RGSpider1 -a start_url=https://www.odu.edu/ -a domain=odu.edu -a university="Old Dominion University  Norfolk"
scrapy crawl RGSpider1 -a start_url=http://www.pace.edu -a domain=pace.edu -a university="Pace University-New York  New York"
scrapy crawl RGSpider1 -a start_url=https://case.edu/ -a domain=case.edu -a university="Case Western Reserve University  Cleveland"
scrapy crawl RGSpider1 -a start_url=http://nau.edu/ -a domain=nau.edu -a university="Northern Arizona University  Flagstaff"
scrapy crawl RGSpider1 -a start_url=http://www.oru.edu/ -a domain=oru.edu -a university="Oral Roberts University"
scrapy crawl RGSpider1 -a start_url=https://www.miamioh.edu/ -a domain=miamioh.edu -a university="Miami University-Oxford"
scrapy crawl RGSpider1 -a start_url=https://www.shu.edu/ -a domain=shu.edu -a university="Seton Hall University"
scrapy crawl RGSpider1 -a start_url=https://wsu.edu/ -a domain=wsu.edu -a university="Washington State University"
scrapy crawl RGSpider1 -a start_url=http://www.uc.edu/ -a domain=uc.edu -a university="University of Cincinnati"
scrapy crawl RGSpider1 -a start_url=https://www.uidaho.edu/ -a domain=uidaho.edu -a university="University of Idaho"
scrapy crawl RGSpider1 -a start_url=http://www.ncat.edu/ -a domain=ncat.edu -a university="North Carolina Agricultural and Technical State University"
scrapy crawl RGSpider1 -a start_url=http://www.uh.edu/ -a domain=uh.edu -a university="University of Houston"
scrapy crawl RGSpider1 -a start_url=https://www.ecu.edu/ -a domain=ecu.edu -a university="East Carolina University"
scrapy crawl RGSpider1 -a start_url=http://www.arizona.edu/ -a domain=arizona.edu -a university="University of Arizona"
scrapy crawl RGSpider1 -a start_url=http://missouri.edu/ -a domain=missouri.edu -a university="University of Missouri-Columbia"
scrapy crawl RGSpider1 -a start_url=http://www.immaculata.edu/ -a domain=immaculata.edu -a university="Immaculata University"
scrapy crawl RGSpider1 -a start_url=http://www.purdue.edu/ -a domain=purdue.edu -a university="Purdue University"
scrapy crawl RGSpider1 -a start_url=http://www.scsu.edu/ -a domain=scsu.edu -a university="South Carolina State University"
scrapy crawl RGSpider1 -a start_url=https://www.uri.edu -a domain=uri.edu -a university="University of Rhode Island"
scrapy crawl RGSpider1 -a start_url=https://umaine.edu/ -a domain=umaine.edu -a university="University of Maine"
scrapy crawl RGSpider1 -a start_url=https://www.ucsc.edu/ -a domain=ucsc.edu -a university="University of California-Santa Cruz"
scrapy crawl RGSpider1 -a start_url=https://www.slu.edu/ -a domain=slu.edu -a university="Saint Louis University"
scrapy crawl RGSpider1 -a start_url=http://www.stthomas.edu/ -a domain=stthomas.edu -a university="University of St Thomas"
scrapy crawl RGSpider1 -a start_url=http://www.uky.edu/UKHome/ -a domain=uky.edu -a university="University of Kentucky"
scrapy crawl RGSpider1 -a start_url=https://www.clarkson.edu/ -a domain=clarkson.edu -a university="Clarkson University "
scrapy crawl RGSpider1 -a start_url=http://www.fit.edu/ -a domain=fit.edu -a university="Florida Institute of Technology"
scrapy crawl RGSpider1 -a start_url=https://www.cua.edu/ -a domain=cua.edu -a university="Catholic University of America"
scrapy crawl RGSpider1 -a start_url=http://www.colorado.edu/ -a domain=colorado.edu -a university="University of Colorado"
scrapy crawl RGSpider1 -a start_url=https://www.biola.edu/ -a domain=biola.edu -a university="Biola University"
scrapy crawl RGSpider1 -a start_url=https://udayton.edu/ -a domain=udayton.edu -a university="University of Dayton"
scrapy crawl RGSpider1 -a start_url=http://www.mtu.edu/ -a domain=mtu.edu -a university="Michigan Technological University"
scrapy crawl RGSpider1 -a start_url=https://www.ohio.edu/ -a domain=ohio.edu -a university="Ohio University-Main"
scrapy crawl RGSpider1 -a start_url=https://www.ou.edu/ -a domain=ou.edu -a university="University of Oklahoma Norman"
scrapy crawl RGSpider1 -a start_url=http://www.smumn.edu/ -a domain=smumn.edu -a university="Saint Mary's University of Minnesota"
scrapy crawl RGSpider1 -a start_url=http://www.georgefox.edu/ -a domain=georgefox.edu -a university="George Fox University"
scrapy crawl RGSpider1 -a start_url=https://uiowa.edu/ -a domain=uiowa.edu -a university="University of Iowa"
scrapy crawl RGSpider1 -a start_url=https://www.pacificu.edu/ -a domain=pacificu.edu -a university="Pacific University  Forest Grove"
scrapy crawl RGSpider1 -a start_url=https://www.olemiss.edu/ -a domain=olemiss.edu -a university="University of Mississippi"