#!/bin/bash
cd /data/link_extractor_Rev2/ResearchGateSpider

scrapy crawl RGSpider1 -a start_url=https://www.sgul.ac.uk -a domain=sgul.ac.uk -a university="圣乔治医学院"
scrapy crawl RGSpider1 -a start_url=http://www.york.ac.uk -a domain=york.ac.uk -a university="约克大学(英国)"
scrapy crawl RGSpider1 -a start_url=http://www.uea.ac.uk -a domain=uea.ac.uk -a university="东英吉利大学"
